"""Type stubs for the nanobind-built _core extension."""

def xlsx_read(path: str) -> list[tuple[int, int, str]]: ...
def xlsx_write(path: str, cells: list[tuple[int, int, str, object]]) -> None: ...
