"""Type stubs for the nanobind-built _core extension."""

from typing import Any

def xlsx_read(path: str) -> list[tuple[str, int, int, str]]: ...
def xlsx_write(path: str, cells: list[tuple[Any, ...]]) -> None: ...
